### ISSUE TITLE
node process crashes with error in metroplex+leverage

### ISSUE THREAD

**Issue by siddo420** [primus/metroplex#12]
I am using the latest metroplex and primus branches and when I kill node process using ^C on MacOSX, it crashes with following trace.

```
2015-10-15T13:53:44.968Z - error: uncaughtException: Connection is closed. 
date=Thu Oct 15 2015 09:53:44 GMT-0400 (EDT), pid=6407, uid=501, gid=20, cwd=/test3, execPath=/usr/local/bin/iojs, version=v4.0.0, argv=[/usr/local/bin/iojs, /test3/app.js], rss=103784448, heapTotal=81414656, heapUsed=60043736, loadavg=[2.8427734375, 2.58837890625, 4.53515625], uptime=10027, 

trace=[column=21, file=/test3/node_modules/metroplex/node_modules/leverage/index.js, function=Leverage.seval, line=549, method=seval, native=false, 
column=21, file=/test3/node_modules/metroplex/node_modules/leverage/index.js, function=Leverage.evals [as annihilate], line=659, method=evals [as annihilate], native=false, 
column=22, file=/test3/node_modules/metroplex/metroplex.js, function=Metroplex.unregister, line=141, method=unregister, native=false, 
column=15, file=/test3/node_modules/metroplex/index.js, function=Primus.close, line=23, method=close, native=false, 
column=17, file=/test3/node_modules/primus/node_modules/asyncemit/index.js, function=each, line=63, method=null, native=false, 
column=5, file=/test3/node_modules/primus/node_modules/asyncemit/index.js, function=Primus.asyncemit, line=71, method=asyncemit, native=false, 
column=10, file=/test3/node_modules/primus/index.js, function=Primus.close, line=946, method=close, native=false, 
column=12, file=/test3/node_modules/primus/index.js, function=[object Object].close, line=925, method=close, native=false, 
column=15, file=timers.js, function=Timer.listOnTimeout, line=89, method=listOnTimeout, native=false], stack=[Error: Connection is closed.,     at Leverage.seval (/test3/node_modules/metroplex/node_modules/leverage/index.js:549:21),     at Leverage.evals [as annihilate] (/test3/node_modules/metroplex/node_modules/leverage/index.js:659:21),     at Metroplex.unregister (/test3/node_modules/metroplex/metroplex.js:141:22),     at Primus.close (/test3/node_modules/metroplex/index.js:23:15),     at each (/test3/node_modules/primus/node_modules/asyncemit/index.js:63:17),     at Primus.asyncemit (/test3/node_modules/primus/node_modules/asyncemit/index.js:71:5),     at Primus.close (/test3/node_modules/primus/index.js:946:10),     at [object Object].close (/test3/node_modules/primus/index.js:925:12),     at Timer.listOnTimeout (timers.js:89:15)]
```

**Comment by lpinca** [comment]
Can you try to installe metroplex#master and see if the same happens?
```
npm i primus/metroplex
```
If it is the case can you please post a minimal test to reproduce the issue?

**Comment by siddo420** [comment]
Ok, will try but might take long time

**Comment by lpinca** [comment]
`leverage` is no longer used, I close this.
